import { objectType } from "nexus";

export const UserType = objectType({
  name: "User",
  definition(t) {
    t.id("userId", {
      description: "Unique ID for user generated by Auth0",
    })
	t.string("name", {
		description: "Name of user",
	})
	t.string("email", {
		description: "Email of user",
	})
	t.list.field('projects', {
		type: 'Project',
		description: 'Projects created by user',
		resolve() {
			return []
		}
	})
  },
});

export * from './queries';
export * from './mutations';


